
import { Game } from '../models/game.model';

export const INITIAL_GAMES: Game[] = [
  {
    id: 1,
    name: '国际象棋',
    image: 'https://picsum.photos/seed/chess/400/300',
    description: '一款双人对弈的策略棋盘游戏，在一个有64个黑白相间方格的棋盘上进行。',
    players: { min: 2, max: 2 },
    playTime: { min: 20, max: 120 },
    // FIX: Changed from '高' to 'High' to match the 'Game' interface type.
    complexity: 'High',
    category: '抽象策略',
    mechanics: ['网格移动', '吃子'],
    components: ['棋盘', '棋子'],
    rules: '每一方都以16个棋子开始：一王、一后、双车、双马、双象和八兵。游戏的目标是将死对方的王，即让其处于一个无法逃脱的被攻击状态。',
    aiAnalysis: {
      coreFun: '通过深思熟虑和战术规划，在智力上战胜对手的挑战。',
      keyDecisions: '决定展开哪个棋子，控制棋盘中心，以及把握进攻时机。',
      potentialFlaws: '在高水平对局中容易出现和棋。高技能门槛可能让新手望而却步。',
      designImpact: '纯策略游戏的典范，其棋子移动和棋盘控制的概念影响了无数后来的游戏。',
    },
    variants: ['费舍尔任意制象棋', '疯狂象棋'],
  },
  {
    id: 2,
    name: '围棋',
    image: 'https://picsum.photos/seed/go/400/300',
    description: '一款双人对弈的抽象策略棋盘游戏，目标是比对手占据更多的领地。',
    players: { min: 2, max: 2 },
    playTime: { min: 30, max: 180 },
    // FIX: Changed from '极高' to 'Very High' to match the 'Game' interface type.
    complexity: 'Very High',
    category: '抽象策略',
    mechanics: ['区域控制', '领地建设', '吃子'],
    components: ['棋盘 (19x19)', '棋子 (黑白)'],
    rules: '双方轮流将棋子放置在棋盘的交叉点上。目标是通过包围领地和吃掉对方的棋子，来控制比对手更大的区域。',
    aiAnalysis: {
      coreFun: '从简单的规则中涌现出的复杂性，创造了深刻而富有禅意的战略体验。',
      keyDecisions: '在获取领地和进行战术战斗之间取得平衡，决定何时开战以及何时脱先（在别处落子）。',
      potentialFlaws: '计分方式对初学者可能不直观。一个失误可能会导致连锁性的灾难后果。',
      designImpact: '极简主义设计的杰作，展示了如何从极少的规则中产生深不可测的深度。',
    },
    variants: ['吃子棋', '联棋'],
  },
  {
    id: 3,
    name: '国际跳棋',
    image: 'https://picsum.photos/seed/checkers/400/300',
    description: '一款双人策略棋盘游戏，棋子沿对角线移动，并通过跳过对方棋子来进行强制吃子。',
    players: { min: 2, max: 2 },
    playTime: { min: 15, max: 30 },
    // FIX: Changed from '低' to 'Low' to match the 'Game' interface type.
    complexity: 'Low',
    category: '抽象策略',
    mechanics: ['网格移动', '强制吃子'],
    components: ['棋盘', '棋子'],
    rules: '玩家沿对角线向前移动自己的棋子。如果相邻的对角线方格上有对方的棋子，可以通过跳过它来吃掉。目标是吃掉对方所有的棋子或使其无法移动。',
    aiAnalysis: {
      coreFun: '多次连跳带来的连锁反应的满足感，以及设置吃子陷阱的战术谜题。',
      keyDecisions: '选择进行哪次吃子，为获得位置优势而牺牲棋子，以及将棋子送到对方底线升变为“王”。',
      potentialFlaws: '游戏可被“破解”，意味着掌握最优策略的玩家可以强制获胜或和棋。',
      designImpact: '是抽象策略游戏的入门之选，教授了强制移动和棋子升变等核心概念。',
    },
    variants: ['百格跳棋', '自杀跳棋'],
  },
  {
    id: 4,
    name: '桥牌',
    image: 'https://picsum.photos/seed/bridge/400/300',
    description: '一种使用标准52张扑克牌的吃墩游戏，由四名玩家组成两个搭档进行对抗。',
    players: { min: 4, max: 4 },
    playTime: { min: 60, max: 180 },
    // FIX: Changed from '高' to 'High' to match the 'Game' interface type.
    complexity: 'High',
    category: '卡牌游戏',
    mechanics: ['吃墩', '叫牌', '团队合作'],
    components: ['标准52张扑克牌'],
    rules: '游戏分为两个阶段：叫牌和打牌。玩家通过叫牌来确定一个“定约”，即搭档需要赢得的墩数。打牌阶段，玩家需跟出同花色的牌，并试图用最大的牌赢得这一墩。',
    aiAnalysis: {
      coreFun: '融合了逻辑、推理和与搭档的沟通，共同智取对手。',
      keyDecisions: '根据手牌强度进行准确叫牌，制定打牌策略以最大化赢墩，以及推断对手的手牌。',
      potentialFlaws: '需要固定的四人游戏。叫牌体系的学习曲线可能非常陡峭。',
      designImpact: '吃墩游戏的巅峰之作，具有丰富的战略深度和全球性的竞技场景。',
    },
    variants: ['盘式桥牌', '复式桥牌'],
  },
  {
    id: 5,
    name: '吹牛骰子',
    image: 'https://picsum.photos/seed/liarsdice/400/300',
    description: '一类适合两人或多人玩的骰子游戏，需要具备欺骗和识破对手骗局的能力。',
    players: { min: 2, max: 6 },
    playTime: { min: 15, max: 30 },
    // FIX: Changed from '低' to 'Low' to match the 'Game' interface type.
    complexity: 'Low',
    category: '骰子游戏',
    mechanics: ['掷骰', '叫价', '吹牛', '玩家淘汰'],
    components: ['每位玩家5个骰子', '每位玩家一个骰盅'],
    rules: '每位玩家在自己的骰盅里摇骰子。然后，玩家轮流就所有玩家骰子中某个点数的总数量进行叫价，叫价必须比前一位高。玩家可以选择继续加价，或挑战前一位的叫价（“开”）。开盅后，如果叫价属实，挑战者输掉一个骰子；反之，叫价者输掉一个骰子。',
    aiAnalysis: {
      coreFun: '吹牛和抓吹牛所带来的社交紧张感，与概率评估相结合。',
      keyDecisions: '判断何时进行安全叫价，何时进行激进的吹牛，以及通过观察对手来决定何时挑战。',
      potentialFlaws: '玩家淘汰机制可能导致部分玩家提前出局，无事可做。',
      designImpact: '一款易于上手的经典吹牛游戏，但提供了惊人的心理博弈深度。',
    },
    variants: ['公共手牌', '不同的叫价规则'],
  },
];
